### ISSUE TITLE
Occasional `OpenURI::HTTPError: 404 Not Found` starting ~3/9/2018

### ISSUE THREAD

**Issue by xinranxiao** [RubyMoney/google_currency#65] opened 2018-03-12 22:48 UTC
Has anyone else been getting occasional `OpenURI::HTTPError: 404 Not Found` errors when trying to fetch rates?

```
open-uri.rb" line 363 in open_http
open-uri.rb" line 741 in buffer_open
open-uri.rb" line 212 in block in open_loop
open-uri.rb" line 210 in catch
open-uri.rb" line 210 in open_loop
open-uri.rb" line 151 in open_uri
open-uri.rb" line 721 in open
open-uri.rb" line 729 in read
gems/google_currency-3.4.0/lib/money/bank/google_currency.rb" line 133 in fetch_rate
```

Ruby: 2.4.3
Example URL that it tries to hit: http://finance.google.com/finance/converter?a=1&from=USD&to=EUR

I can't seem to deterministically reproduce this... has anyone else been running into this recently?

**Comment by jirihradil** [comment] 2018-03-13 08:04
The same for me. Started yesterday (3/12/2018) and occurs occasionally for different currencies converted to USD (AUD, MAD, KES). When repeating, it's OK. Guess something to do with the Google's endpoint?

**Comment by jirihradil** [comment] 2018-03-13 13:17
Full stack:

```
Monetize.from_string(BigDecimal.new('100'), 'KWD').as_us_dollar.to_s

OpenURI::HTTPError: 404 Not Found
	from /home/ec2-user/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/open-uri.rb:358:in `open_http'
	from /home/ec2-user/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/open-uri.rb:736:in `buffer_open'
	from /home/ec2-user/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/open-uri.rb:211:in `block in open_loop'
	from /home/ec2-user/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/open-uri.rb:209:in `catch'
	from /home/ec2-user/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/open-uri.rb:209:in `open_loop'
	from /home/ec2-user/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/open-uri.rb:150:in `open_uri'
	from /home/ec2-user/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/open-uri.rb:716:in `open'
	from /home/ec2-user/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/open-uri.rb:724:in `read'
	from /home/ec2-user/.rvm/gems/ruby-2.2.5/bundler/gems/google_currency-fa6e8ba366c0/lib/money/bank/google_currency.rb:133:in `fetch_rate'
	from /home/ec2-user/.rvm/gems/ruby-2.2.5/bundler/gems/google_currency-fa6e8ba366c0/lib/money/bank/google_currency.rb:103:in `get_rate'
	from /home/ec2-user/.rvm/gems/ruby-2.2.5/gems/money-6.10.1/lib/money/bank/variable_exchange.rb:110:in `exchange_with'
	from /home/ec2-user/.rvm/gems/ruby-2.2.5/gems/money-6.10.1/lib/money/money.rb:436:in `exchange_to'
	from /home/ec2-user/.rvm/gems/ruby-2.2.5/gems/money-6.10.1/lib/money/money.rb:449:in `as_us_dollar'
	from (irb):8
	from /home/ec2-user/.rvm/gems/ruby-2.2.5/gems/railties-5.0.4/lib/rails/commands/console.rb:65:in `start'
	from /home/ec2-user/.rvm/gems/ruby-2.2.5/gems/railties-5.0.4/lib/rails/commands/console_helper.rb:9:in `start'
	from /home/ec2-user/.rvm/gems/ruby-2.2.5/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /home/ec2-user/.rvm/gems/ruby-2.2.5/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /home/ec2-user/.rvm/gems/ruby-2.2.5/gems/railties-5.0.4/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:9:in `require'
	from bin/rails:9:in `<main>'
```

**Comment by adrianwantsa** [comment] 2018-03-13 16:13
+1

**Comment by jirihradil** [comment] 2018-03-13 21:16
I did a prefetch of all currencies as a workaround in Ruby. If it throws 404, I repeat it as long as it fails. Also changed ttl to 30 days:

```ruby
Money::Bank::GoogleCurrency.ttl_in_seconds = 2592000 # 30 days
```

```ruby
GOOGLE_UNSUPPORTED_CURRENCIES = ["BYR", "GGP", "IMP", "IRR", "JEP", "PRB", "MNK", "RMB", "TVD", "SSP", "STD", "VEF", "VND", "ZMK", "ZWD"];

ISO4217::Currency.currencies.keys.sort.each {|c| p c; next if GOOGLE_UNSUPPORTED_CURRENCIES.include?(c); p Monetize.from_string(BigDecimal.new('100'), c).as_us_dollar.to_s; sleep 1; }

**Comment by jirihradil** [comment] 2018-03-14 11:08
Errors are increasing. Is the endpoint going to die? Guess that's not very probable that Google has unstable finance converter for couple of days.

**Comment by jirihradil** [comment] 2018-03-14 15:50
Error rate is still increasing. Moved to https://github.com/spk/money-open-exchange-rates which uses different endpoint. Works flawlessly.

**Comment by adrianwantsa** [comment] 2018-03-14 16:23
I haven't seen the error for 24 hours. But also have https://github.com/spk/money-open-exchange-rates ready to go, if need be.

**Comment by dmcwilliams** [comment] 2018-03-15 12:42
I have seen several errors this morning so I've begun looking into https://github.com/spk/money-open-exchange-rates

**Comment by antstorm** [comment] 2018-03-15 21:56
Yeah, it looks like Google is winding down their exchange rates page. I'm getting occasional redirects to "Finance" section of google search.

**Comment by jirihradil** [comment] 2018-03-15 22:02
Just FYI - using https://github.com/spk/money-open-exchange-rates for 2 days instead this gem and can say it's a good successor.
Good speed to you, google_currency, served us for 7 years, thank you and thanks all the contributors!

**Comment by Paludis** [comment] 2018-03-16 04:15
Having the same issue, will check out https://github.com/spk/money-open-exchange-rates

**Comment by lukaVarga** [comment] 2018-03-17 15:35
It looks like it is constantly redirecting to the google search page now..

**Comment by edlebert** [comment] 2018-03-19 20:45
I just created another gem that uses openexchangerates.org: https://github.com/edlebert/money-oxr

**Comment by antstorm** [comment] 2018-03-19 21:20
@edlebert just curious why did you decide to build another gem instead of improving the existing one?

**Comment by edlebert** [comment] 2018-03-19 22:19
@antstorm Other than getting the rates from the same source, the gems are pretty different.  I don't mean any disrespect, but some of the functionality provided by the original gem doesn't behave like users expect.  And I don't think the author is too keen on making changes in those areas. (see here: https://github.com/spk/money-open-exchange-rates/issues/38) First and foremost I need a useful and reliable bank, so the easiest option was just to create another option.

**Comment by Paludis** [comment] 2018-03-20 02:32
@edlebert thank you, looks great!

**Comment by sbleon** [comment] 2018-03-20 21:29
https://github.com/edlebert/money-oxr is working well for me to. Thanks, @edlebert !

It seems like `money-oxr` will do conversions from any currency to any currency, even on the https://openexchangerates.org free plan. I had thought I was going to have to sign up for a paid account or write my own "convert X to Y via USD" routine, but the gem is pretty-much a drop-in replacement for `google_currency`, with just a touch of configuration required.

**Comment by antstorm** [comment] 2018-03-20 21:49
@edlebert makes sense, but I'd advice to focus the effort rather than diluting it if possible

**Comment by robskrob** [comment] 2018-03-21 19:00
@edlebert just out of curiosity, why did you make a new gem vs using this one which has been maintained for roughly 3 years now https://github.com/spk/money-open-exchange-rates ? `money-open-exchange-rates` appears to fix the problem that originally started this issue.

**Comment by edlebert** [comment] 2018-03-22 00:53
@antstorm I understand, but in some cases, the author isn't willing to take their project in the direction you want, which is the case here.  Thanks again for this awesome gem, and I hope we can all continue to enjoy free and easy currency-exchanges for years to come :)

**Comment by spk** [comment] 2018-03-23 18:17
Hello, if you where talking about [money-open-exchange-rates](https://github.com/spk/money-open-exchange-rates) @edlebert, I don't see any pull requests or issues where I was not willing to accept improvement or direction changes, cheers

**Comment by edlebert** [comment] 2018-03-24 13:12
@spk I don't mean any disrespect. I never said you were unwilling to accept improvement. You're very friendly and willing to accept PRs, etc. Several of the Issues in money-open-exchange-rates have expressed confusion surrounding caching/TTL/auto-refresh.  Your response has always been for users to set up cron or heroku scheduler tasks to manage auto-refresh and re-writing the cache (I'm not linking them all here). That's a totally valid design decision, and it's one you're obviously comfortable with keeping.  For myself, I wanted something similar to google_currency.

Also, no offense to anyone, but I'm not going to respond to any more "why" questions here about money-oxr here.  Feel free to open an issue or PR, or contact me directly (can you even do that on github?)

**Comment by spk** [comment] 2018-03-24 14:55
Thanks for your reply @edlebert, I did not feel any disrespect but I just wanted to said that I'm not against change and I'm always glad to have feedback on projects, the issues are here https://github.com/spk/money-open-exchange-rates/issues/37 and https://github.com/spk/money-open-exchange-rates/issues/38; cheers

**Comment by ThinkAndRun** [comment] 2018-03-26 12:00
I've added PR to fix it: https://github.com/RubyMoney/google_currency/pull/71

**Comment by antstorm** [comment] 2018-03-26 19:39
Just pushed a new version with updated URL — `3.4.1`. Would appreciate if people who still use it could update it and tell me if it works consistently.

**Comment by antstorm** [comment] 2018-03-29 20:16
@Onikoroshi you should `bundle update google_currency` instead, since **it's not** a dependency of `money-rails` or `money`. It should be a separate entry in your Gemfile.

**Comment by antstorm** [comment] 2018-03-31 19:35
@Onikoroshi no problem, glad that it works now

**Comment by apuente93** [comment] 2018-05-31 17:15
This is still causing issues OpenURI::HTTPError: 404 Not Found

**Comment by kissrobber** [comment] 2018-06-01 03:43
I got 404 errors today and 5days ago

**Comment by antstorm** [comment] 2018-06-03 10:43
This is caused by network conditions, instability of google's API (looks like it's not really supported). If you are still using this gem I'd suggest putting some retry logic around the call.

**Comment by bretweinraub** [comment] 2018-06-04 08:05
http://finance.google.com/finance/converter?a=1&from=USD&to=EUR

![image](https://user-images.githubusercontent.com/214091/40905623-d094bfb4-67de-11e8-9996-408af6b4bf88.png)

**Comment by wikiti** [comment] 2018-06-04 08:34
Looks like the current path (`/bctzjpnsun/converter`) is throwing 404 errors:

https://finance.google.com/bctzjpnsun/converter?a=1&from=USD&to=EUR

**Comment by bretweinraub** [comment] 2018-06-04 08:35
I threw in the towel on Google Finance and have hacked together something simple using fixer.io.

**Comment by CarlosIgnacioGo** [comment] 2018-06-04 15:16
OpenURI::HTTPError: 404 Not Found

**Comment by apuente93** [comment] 2018-06-04 15:19
Thanks for the reply. I suggest moving to https://github.com/spk/money-open-exchange-rates. Works like a charm without this error.

**Comment by antstorm** [comment] 2018-06-06 08:39
Have a look at https://github.com/RubyMoney/money#implementations for a list of alternatives as the Google converter is getting really unstable

**Comment by antprt** [comment] 2018-06-11 08:10
Is mainteined the gem?

From the last 15 days I have the same error: OpenURI::HTTPError: 404 Not Found

**Comment by antstorm** [comment] 2018-06-12 07:43
@antprt I suggest you getting yourself familiar with the thread before posting nonsense

**Comment by absyah** [comment] 2018-08-28 02:14
Today status: `OpenURI::HTTPError: 404 Not Found`

**Comment by antstorm** [comment] 2018-08-29 11:07
@absyah thanks for reporting.

I've updated the README with a warning of this issue — https://github.com/RubyMoney/google_currency#warning

**Comment by ravindra9278** [comment] 2020-03-08 17:05
Still Getting 404 Error
```
> bank = Money::Bank::GoogleCurrency.new
> bank.get_rate(:GBP, :USD).to_f

> Traceback (most recent call last):
        1: from (irb):15
OpenURI::HTTPError (404 Not Found)
```

**Comment by joshuapinter** [comment] 2021-02-11 16:34
Just wanted to add to here. We ended up replacing `google_currency` with [`eu_central_bank`](https://github.com/RubyMoney/eu_central_bank) and it was very easy and worked great. It's part of `RubyMoney` so it should be well maintained. Basic replacement looks like this: 

```ruby
eu_central_bank = EuCentralBank.new

eu_central_bank.update_rates # TODO: Make this use a cache in a shared directory and just update it every day.

Money.default_bank = eu_central_bank
```

Definitely a good option to consider.

**Closed** 2021-02-28 20:51 UTC
